# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on MacOS

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest 

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

      # Set up a matrix to run the following 3 configurations:
    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler on Linux
      run: |
        brew install cmake git
    - name: Create build in CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DGITHUB_ACTION=ON -DDEX_TESTS=ON
    - name: Build with cmake
      run: cmake --build build/ -j
    - name: Install with cmake
      run: sudo cmake --install build/
    - name : Run tests
      run: ctest --test-dir build/ --output-on-failure

    - name: Verify built shuriken-dump exit code
      run: |
        set +e # Prevent the script from exiting immediately on error
        ./build/shurken-dump/shuriken-dump
        exit_code=$?
        set -e # Re-enable immediate script exit on error

    - name: Verify installed shuriken-dump exit code
      run: |
        set +e # Prevent the script from exiting immediately on error
        shuriken-dump
        exit_code=$?
        set -e # Re-enable immediate script exit on error
        if [ $exit_code -eq 255 ]; then
          echo "compiled shuriken-dump exited with the expected exit code."
        else
          echo "Unexpected exit code from shuriken-dump: $exit_code"
          exit 1
        fi
    - name: Uninstall target and verify uninstall target works
      run: |
        set +e 
        sudo cmake --build build/ --target uninstall   
        ls /usr/local/ -R | grep "shuriken" 
        if [ $? -eq 1 ]; then 
          echo "Uninstall target worked as expected"  
          exit 0  
        else  \ 
          echo "Uninstall target did not work as expected" 
          exit 1  
        fi
        set -e

