name: Python installer

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
env:
  GITHUB_ACTION: ON 
jobs:
  build:
    runs-on: ubuntu-24.04
      # clang custom placeholder
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Setup compiler on Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13
        echo "CC=gcc-13" >> $GITHUB_ENV
        echo "CXX=g++-13" >> $GITHUB_ENV
    - name: Display compiler version
      run: $CC --version
    - name: Install cmake
      run: sudo apt-get install cmake
    - name: Install git
      run: sudo apt install git
    - name: Set up venv
      run: |
        python3 -m venv .venv && source .venv/bin/activate
        pip install -vvv git+https://github.com/Fare9/Shuriken-Analyzer.git@main#subdirectory=shuriken/bindings/Python/
        python3 -c "from shuriken import *"
